spring:
  profiles:
    active: test
    
ccc: 曹晓

    
---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
    ccc: caoxiao
caoxiao: 111
---   
spring:
  profiles: test
  application:
    name: springcloud-config-test
    caoxiao: 111
caoxiao: 222
