spring:
  profiles:
    active: dev
    
ccc: 曹晓

    
    
--- 
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
      
---     
spring:
  profiles: test
  application:
    name: springcloud-config-test
